services:
  - type: web
    name: nova-sonic-novasys
    env: python
    runtime: python-3.12
    region: oregon
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: PYTHONUNBUFFERED
        value: "1"
